// Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "url": "sethukumarj.com",
            "email": "sethukumarj.76@gmail.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/approve-event": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin-Event Management"
                ],
                "summary": "approves the event for admin",
                "operationId": "approves event",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Event Name : ",
                        "name": "title",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/admin/create-event": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin-Event Management"
                ],
                "summary": "Create event",
                "operationId": "Create event from admin",
                "parameters": [
                    {
                        "description": "Create event",
                        "name": "CreateEvent",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.Events"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/admin/list-events": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin-Event Management"
                ],
                "summary": "list all upcoming events for admin",
                "operationId": "list all upcoming events",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number: ",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page capacity : ",
                        "name": "pagesize",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "List event by approved non approved : ",
                        "name": "approved",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/admin/list-organizations": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin-Organization Management"
                ],
                "summary": "list all pending organizations for admin",
                "operationId": "list all organization with status",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number: ",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page capacity : ",
                        "name": "pagesize",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "List organization based on status: ",
                        "name": "applicationStatus",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/admin/list-users": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin-User Profile"
                ],
                "summary": "list all active users for admin",
                "operationId": "list all active users",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Page number: ",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Page capacity : ",
                        "name": "pagesize",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/admin/login": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin Authentication"
                ],
                "summary": "Login for Admin",
                "operationId": "Admin Login",
                "parameters": [
                    {
                        "description": "adminlogin: ",
                        "name": "AdminLogin",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.Login"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/admin/register-organization": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin-Organization Management"
                ],
                "summary": "Resginter the organization",
                "operationId": "Register organization",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "orgStatus id : ",
                        "name": "orgstatusid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/admin/reject-organization": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin-Organization Management"
                ],
                "summary": "Rejects the organization",
                "operationId": "Reject organization",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "orgStatus id : ",
                        "name": "orgstatusid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/admin/search-event": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin-Event Management"
                ],
                "summary": "Search Event",
                "operationId": "search event with string",
                "parameters": [
                    {
                        "type": "string",
                        "description": "search string: ",
                        "name": "search",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/admin/signup": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin Authentication"
                ],
                "summary": "SignUp for Admin",
                "operationId": "Admin signup",
                "parameters": [
                    {
                        "description": "admin signup with username, phonenumber email ,password",
                        "name": "RegisterAdmin",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.Admins"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/admin/token-refresh": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin Authentication"
                ],
                "summary": "Refresh token for admin",
                "operationId": "Admin RefreshToken",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token string: ",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/admin/vipfy-user": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin-User Profile"
                ],
                "summary": "makes the user vip",
                "operationId": "make vip user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User Name : ",
                        "name": "username",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/organization/admin/add-members": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Organizaton-Admin Role"
                ],
                "summary": "Add Admins",
                "operationId": "Add admins for the organizaition",
                "parameters": [
                    {
                        "description": "addMembers:",
                        "name": "addMembers",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.AddMembers"
                            }
                        }
                    },
                    {
                        "type": "string",
                        "description": "OrganizationName: ",
                        "name": "organizationName",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "member role",
                        "name": "memberrole",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/organization/admin/admit-member": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Organizaton-Admin Role"
                ],
                "summary": "Admit member",
                "operationId": "Admit member",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "JoinStatusId: ",
                        "name": "joinstatusid",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Organization Name :",
                        "name": "organizationName",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "member role",
                        "name": "role",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/organization/admin/delete-member": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Organizaton-Admin Role"
                ],
                "summary": "remove member",
                "operationId": "remvoe member",
                "parameters": [
                    {
                        "type": "string",
                        "description": "organizationName: ",
                        "name": "organizationName",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Username :",
                        "name": "userName",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/organization/admin/list-members": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Organizaton-Admin Role"
                ],
                "summary": "List Members",
                "operationId": "List Members of the organization",
                "parameters": [
                    {
                        "type": "string",
                        "description": "OrganizationName: ",
                        "name": "organizationName",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Member role :",
                        "name": "memberRole",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/organization/admin/update-role": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Organizaton-Admin Role"
                ],
                "summary": "Update member role",
                "operationId": "update  member role",
                "parameters": [
                    {
                        "type": "string",
                        "description": "organizationName: ",
                        "name": "organizationName",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Username :",
                        "name": "userName",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Role to update :",
                        "name": "updatedRole",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/organization/create-event": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Organization"
                ],
                "summary": "Create event by organization",
                "operationId": "Create event from organization",
                "parameters": [
                    {
                        "type": "string",
                        "description": "organizationName",
                        "name": "organizationName",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Create event",
                        "name": "CreateEvent",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.Events"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/organization/event/accept-application": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Organization"
                ],
                "summary": "accept the application for participate in the event",
                "operationId": "Accept application",
                "parameters": [
                    {
                        "type": "string",
                        "description": "organizationName: ",
                        "name": "organizationName",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "orgStatus id : ",
                        "name": "applicationstsid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/organization/event/create-poster": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Organization-Event-Poster Management"
                ],
                "summary": "Create Poster by organization",
                "operationId": "Create Poster from organization",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Event id",
                        "name": "EventId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Create poster",
                        "name": "CreatePoster",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.Posters"
                        }
                    },
                    {
                        "type": "string",
                        "description": "organizationName: ",
                        "name": "organizationName",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/organization/event/delete-event": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Organization"
                ],
                "summary": "delete event",
                "operationId": "Delete event",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Title: ",
                        "name": "title",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "organizationName: ",
                        "name": "organizationName",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/organization/event/delete-poster": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Organization-Event-Poster Management"
                ],
                "summary": "delete poster",
                "operationId": "Delete poster",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Title: ",
                        "name": "title",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Title: ",
                        "name": "eventid",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "organizationName: ",
                        "name": "organizationName",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/organization/event/get-posterbytitle": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Organization-Event-Poster Management"
                ],
                "summary": "Get poster by title",
                "operationId": "Get event by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Title: ",
                        "name": "title",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "event id: ",
                        "name": "eventid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/organization/event/get-posters": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Organization-Event-Poster Management"
                ],
                "summary": "Search Event from user side",
                "operationId": "Get posters Order by Event",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Posters under event : ",
                        "name": "Eventid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/organization/event/list-applications": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Organization"
                ],
                "summary": "list all pending application of participant",
                "operationId": "list all application with status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "event Name: ",
                        "name": "eventname",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page number: ",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page capacity : ",
                        "name": "pagesize",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "organizationName: ",
                        "name": "organizationName",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "List application based on status: ",
                        "name": "applicationStatus",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/organization/event/list-questions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "FAQA-organization-volunteers\u003e"
                ],
                "summary": "list all Asked questions",
                "operationId": "list all asked questions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "organizationName",
                        "name": "organizationName",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Event title: ",
                        "name": "title",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/organization/event/post-answer": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "FAQA-organization-volunteers\u003e"
                ],
                "summary": "Post Answer function",
                "operationId": "User Post Answer",
                "parameters": [
                    {
                        "type": "string",
                        "description": "organizationName",
                        "name": "organizationName",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Getting the id of the question",
                        "name": "faqaid",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Post Answer",
                        "name": "PostAnswer",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.Answers"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/organization/event/promote": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Organizaton-Admin Role"
                ],
                "summary": "Promote",
                "operationId": "promote event",
                "parameters": [
                    {
                        "type": "string",
                        "description": "event name",
                        "name": "eventName",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "plan",
                        "name": "plan",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "email",
                        "name": "email",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/organization/event/update-event": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Organization"
                ],
                "summary": "update event",
                "operationId": "Update event",
                "parameters": [
                    {
                        "type": "string",
                        "description": "event title",
                        "name": "title",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "organizationName: ",
                        "name": "organizationName",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "update Event with new body",
                        "name": "UpdateEvent",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.Events"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/organization/get-organization": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User-Organization Management"
                ],
                "summary": "Get Organization",
                "operationId": "Get Organizaition by name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "OrganizationName: ",
                        "name": "organizationName",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/organization/join-requests": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Organizaton-Admin Role"
                ],
                "summary": "List Join Requests",
                "operationId": "Join requests to organization",
                "parameters": [
                    {
                        "type": "string",
                        "description": "OrganizationName: ",
                        "name": "organizationName",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/organization/reject-application": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Organization"
                ],
                "summary": "Rejects the application for participate in the event",
                "operationId": "Reject application",
                "parameters": [
                    {
                        "type": "string",
                        "description": "organizationName: ",
                        "name": "organizationName",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "applicationstsid  : ",
                        "name": "applicationstsid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/user/accept-invitation": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User-Organization Management"
                ],
                "summary": "Accept invitation to join an organization",
                "operationId": "Accept invitation to join organization",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token: ",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/user/apply-event": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User-Event Management"
                ],
                "summary": "ApplyEvent",
                "operationId": "Apply event",
                "parameters": [
                    {
                        "type": "string",
                        "description": "event name",
                        "name": "eventName",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Apply event",
                        "name": "ApplyEvent",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.ApplicationForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/user/create-event": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User-Event Management"
                ],
                "summary": "Create event",
                "operationId": "Create event from user",
                "parameters": [
                    {
                        "description": "Create event",
                        "name": "CreateEvent",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.Events"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/user/create-organization": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User-Organization Management"
                ],
                "summary": "Create Organization",
                "operationId": "Create Organizatioin from user",
                "parameters": [
                    {
                        "description": "Create organization",
                        "name": "CreateOrganization",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.Organizations"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/user/event/post-question": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "FAQA-user"
                ],
                "summary": "Post Question function",
                "operationId": "User Post Question",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Getting the title of the event",
                        "name": "title",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Getting the title of the event",
                        "name": "organizername",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Post question",
                        "name": "PostQuestion",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.Faqas"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/user/geteventbytitle": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User-Event Management"
                ],
                "summary": "get event by title",
                "operationId": "Get event by title",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Title: ",
                        "name": "title",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/user/join-organization": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User-Organization Management"
                ],
                "summary": "Joining organization",
                "operationId": "Join organization",
                "parameters": [
                    {
                        "type": "string",
                        "description": "organization name: ",
                        "name": "organizationName",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/user/list-approved-events": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User-Event Management"
                ],
                "summary": "list all approved upcoming events",
                "operationId": "list all approved events",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Page number: ",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "Cusat only: ",
                        "name": "cusatonly",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "Online: ",
                        "name": "online",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Sex (options: male, female, any)",
                        "name": "sex",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Page capacity : ",
                        "name": "pagesize",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/user/list-faqas": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "FAQA-user"
                ],
                "summary": "list all Public faqas",
                "operationId": "list all public faqas",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Event title: ",
                        "name": "title",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/user/list-organizations": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User-Organization Management"
                ],
                "summary": "list all registered organizations for user",
                "operationId": "list all registered organizations",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number: ",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page capacity : ",
                        "name": "pagesize",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/user/login": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Authentication"
                ],
                "summary": "Login for users",
                "operationId": "User Login",
                "parameters": [
                    {
                        "description": "userlogin: ",
                        "name": "UserLogin",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.Login"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/user/search-event": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User-Event Management"
                ],
                "summary": "Search Event from user side",
                "operationId": "search event with string by user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "List event by approved non approved : ",
                        "name": "search",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/user/send-verification": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Verification mail"
                ],
                "summary": "Send verification",
                "operationId": "Send verifiation code via email",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Email: ",
                        "name": "email",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/user/signup": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Authentication"
                ],
                "summary": "SignUp for users",
                "operationId": "User SignUp",
                "parameters": [
                    {
                        "description": "user signup with username, phonenumber email ,password",
                        "name": "RegisterUser",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.Users"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/user/sso-google": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Authentication"
                ],
                "summary": "Authenticate With Google",
                "operationId": "Authenticate With Google",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/user/token-refresh": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Authentication"
                ],
                "summary": "Refresh token for users",
                "operationId": "User RefreshToken",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/user/update-password": {
            "patch": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Profile"
                ],
                "summary": "update password",
                "operationId": "Update password",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Email: ",
                        "name": "email",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "update password with new body",
                        "name": "Updatepassword",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/user/update-profile": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Profile"
                ],
                "summary": "update Profileabout",
                "operationId": "Update userprofile",
                "parameters": [
                    {
                        "description": "update profile with new body",
                        "name": "UpdateProfile",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.Bios"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.AddMembers": {
            "type": "object",
            "properties": {
                "members": {
                    "type": "string"
                }
            }
        },
        "domain.Admins": {
            "type": "object",
            "required": [
                "adminname",
                "email",
                "password"
            ],
            "properties": {
                "adminid": {
                    "type": "integer"
                },
                "adminname": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 2
                },
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phonenumber": {
                    "type": "string"
                }
            }
        },
        "domain.Answers": {
            "type": "object",
            "properties": {
                "answer": {
                    "type": "string"
                }
            }
        },
        "domain.ApplicationForm": {
            "type": "object",
            "properties": {
                "about": {
                    "type": "string"
                },
                "college": {
                    "type": "string"
                },
                "company": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "firstname": {
                    "type": "string"
                },
                "github": {
                    "type": "string"
                },
                "lastname": {
                    "type": "string"
                },
                "linkedin": {
                    "type": "string"
                },
                "proffession": {
                    "type": "string"
                }
            }
        },
        "domain.Bios": {
            "type": "object",
            "required": [
                "username"
            ],
            "properties": {
                "about": {
                    "type": "string"
                },
                "devfolio": {
                    "type": "string"
                },
                "githublink": {
                    "type": "string"
                },
                "linkedin": {
                    "type": "string"
                },
                "qualification": {
                    "type": "string"
                },
                "skills": {
                    "type": "string"
                },
                "twitterlink": {
                    "type": "string"
                },
                "username": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 2
                },
                "websitelink": {
                    "type": "string"
                }
            }
        },
        "domain.Events": {
            "type": "object",
            "required": [
                "eventdate",
                "eventpic",
                "organizername",
                "title"
            ],
            "properties": {
                "applicationclosingdate": {
                    "type": "string"
                },
                "applicationleft": {
                    "type": "integer"
                },
                "applicationlink": {
                    "type": "string"
                },
                "cusatonly": {
                    "type": "boolean"
                },
                "eventdate": {
                    "type": "string"
                },
                "eventpic": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "longdiscription": {
                    "type": "string"
                },
                "maxapplications": {
                    "type": "integer"
                },
                "online": {
                    "type": "boolean"
                },
                "organizername": {
                    "type": "string"
                },
                "paid": {
                    "type": "boolean"
                },
                "sex": {
                    "type": "string",
                    "default": "any"
                },
                "shortdiscription": {
                    "type": "string"
                },
                "subevents": {
                    "type": "string"
                },
                "title": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 2
                },
                "websitelink": {
                    "type": "string"
                }
            }
        },
        "domain.Faqas": {
            "type": "object",
            "required": [
                "question"
            ],
            "properties": {
                "question": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 2
                }
            }
        },
        "domain.Login": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "domain.Organizations": {
            "type": "object",
            "required": [
                "organizationname"
            ],
            "properties": {
                "about": {
                    "type": "string"
                },
                "createdat": {
                    "type": "string"
                },
                "linkedin": {
                    "type": "string"
                },
                "logo": {
                    "type": "string"
                },
                "organizationname": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 2
                },
                "websitelink": {
                    "type": "string"
                }
            }
        },
        "domain.Posters": {
            "type": "object",
            "properties": {
                "colour": {
                    "type": "string"
                },
                "discription": {
                    "type": "string"
                },
                "image": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "domain.Users": {
            "type": "object",
            "required": [
                "email",
                "firstname",
                "lastname",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "firstname": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 2
                },
                "lastname": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 1
                },
                "password": {
                    "type": "string"
                },
                "phonenumber": {
                    "type": "string"
                },
                "profile": {
                    "type": "string"
                },
                "username": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 2
                },
                "verification": {
                    "type": "boolean"
                }
            }
        },
        "response.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "errors": {},
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        },
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Go + Gin Radar API",
	Description:      "This is an Events Radar project. You can visit the GitHub repository at https://github.com/SethukumarJ/Events_Radar_Developement",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
